### PR TITLE
Add empty BUILD file to prebuilt_swift_static_framework

### PR DESCRIPTION
**Pull request by thii**
A `BUILD` file is required in order to load the rule directly from this repo.

### CODE REVIEW

**Comment by keith** [comment]
Loading the rule directly from this repo wasn't exactly what we had in mind here. IMO this was more about documenting useful tidbits like this and allowing others to take them and customize them for their needs.

**Comment by thii** [comment]
I see.

**Comment by keith** [comment]
@rahul-malik @kastiglione do you have thoughts on this?

**Comment by kastiglione** [comment]
In general I'm in favor of the idea of publishing rules in this repo, but under conditions. If a rule was rejected elsewhere, and if we had some tests and CI, then I think it could make sense.

**Comment by kastiglione** [comment]
In the mean time, people are free to use [`new_git_repository()`](https://docs.bazel.build/versions/master/be/workspace.html#new_git_repository) and `build_file_content` to pull this into their WORKSPACE.

**Pull request closed without merging**
