### PR TITLE
Use named module maps to allow multiple Swift targets in a same package

### PR DESCRIPTION
**Pull request by thii**

### CODE REVIEW

**Comment by keith** [comment]
Doesn't this have to be `module.modulemap` once it's in the final `.framework`?

**Comment by thii** [comment]
It’ll be renamed when bundled.

**Comment by thii** [comment]
https://github.com/ios-bazel-users/ios-bazel-users/blob/83f69d023b6efee47c2e43dc5472a9474b6f26b1/swift_static_framework/swift_static_framework.bzl#L37

**Comment by keith** [comment]
Thanks!

**Pull request merged**
